const actionNames = {
  GET_TASKS: "GET_TASKS",
  DELETE_TASK: "DELETE_TASK",
  GET_EVENTS: "GET_EVENTS",
  DELETE_EVENT: "DELETE_EVENT",
  APP_ERROR: "APP_ERROR",
  REMOVE_APP_ERROR: "REMOVE_APP_ERROR",
}

export default actionNames
